-- MySQL Script generated by MySQL Workbench
-- Fri Aug 13 05:13:52 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema electrodomesticos_store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema electrodomesticos_store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `electrodomesticos_store` DEFAULT CHARACTER SET utf8mb4 ;
USE `electrodomesticos_store` ;

-- -----------------------------------------------------
-- Table `electrodomesticos_store`.`actualizacion_stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electrodomesticos_store`.`actualizacion_stock` (
  `id_stock` INT(11) NOT NULL,
  `id_prod` INT(11) NOT NULL,
  PRIMARY KEY (`id_stock`, `id_prod`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `electrodomesticos_store`.`cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electrodomesticos_store`.`cargos` (
  `id_cargos` INT(11) NOT NULL,
  `nombre_cargo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_cargos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `electrodomesticos_store`.`cliente_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electrodomesticos_store`.`cliente_usuario` (
  `id` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `edad` INT(11) NULL DEFAULT NULL,
  `tarjeta_credito` INT(16) NULL DEFAULT NULL,
  `telefono` INT(11) NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  `e_mail` VARCHAR(45) NULL DEFAULT NULL,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `electrodomesticos_store`.`compra_presencial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electrodomesticos_store`.`compra_presencial` (
  `id_cliente` INT(11) NOT NULL,
  `id_producto` INT(11) NOT NULL,
  `id_personal` INT(11) NOT NULL,
  PRIMARY KEY (`id_cliente`, `id_personal`, `id_producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `electrodomesticos_store`.`entidad_federativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electrodomesticos_store`.`entidad_federativa` (
  `id` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  INDEX `entidad_sucursal_idx` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `electrodomesticos_store`.`entidad_sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electrodomesticos_store`.`entidad_sucursal` (
  `id_entidad` INT(11) NOT NULL,
  `id_sucursal` INT(11) NOT NULL,
  PRIMARY KEY (`id_entidad`, `id_sucursal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `electrodomesticos_store`.`personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electrodomesticos_store`.`personal` (
  `id` INT(11) NOT NULL,
  `id_cargo` INT(11) NULL DEFAULT NULL,
  `sueldo` FLOAT NULL DEFAULT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `edad` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(85) NULL DEFAULT NULL,
  `e_mail` VARCHAR(45) NULL DEFAULT NULL,
  `horario_entrada` TIME NULL DEFAULT NULL,
  `horario_salida` TIME NULL DEFAULT NULL,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `electrodomesticos_store`.`personal_vale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electrodomesticos_store`.`personal_vale` (
  `id_personal` INT(11) NOT NULL,
  `id_vale` INT(11) NOT NULL,
  PRIMARY KEY (`id_personal`, `id_vale`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `electrodomesticos_store`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electrodomesticos_store`.`producto` (
  `id_producto` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `cantidad` INT(11) NULL DEFAULT NULL,
  `precio` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `electrodomesticos_store`.`reservacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electrodomesticos_store`.`reservacion` (
  `id_cliente` INT(11) NOT NULL,
  `id_producto` INT(11) NOT NULL,
  PRIMARY KEY (`id_cliente`, `id_producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `electrodomesticos_store`.`stock_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electrodomesticos_store`.`stock_productos` (
  `id_stock` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `cantidad` INT(11) NULL DEFAULT NULL,
  `precio` INT(11) NULL DEFAULT NULL,
  `id_sucursal` INT(11) NOT NULL,
  PRIMARY KEY (`id_stock`, `id_sucursal`),
  INDEX `sucursal_idx` (`id_sucursal` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4 PARTITION BY RANGE(`id_sucursal`) PARTITIONS 4( PARTITION part1 VALUES LESS THAN (2),  PARTITION part2 VALUES LESS THAN (3),  PARTITION part3 VALUES LESS THAN (4),  PARTITION part4 VALUES LESS THAN (5)) ;


-- -----------------------------------------------------
-- Table `electrodomesticos_store`.`sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electrodomesticos_store`.`sucursal` (
  `id_sucursal` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_sucursal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `electrodomesticos_store`.`sucursal_personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electrodomesticos_store`.`sucursal_personal` (
  `id_sucursal` INT(11) NOT NULL,
  `id_personal` INT(11) NOT NULL,
  PRIMARY KEY (`id_sucursal`, `id_personal`),
  INDEX `personal_idx` (`id_personal` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4 PARTITION BY RANGE(`id_sucursal`) PARTITIONS 4( PARTITION part1 VALUES LESS THAN (2),  PARTITION part2 VALUES LESS THAN (3),  PARTITION part3 VALUES LESS THAN (4),  PARTITION part4 VALUES LESS THAN (5)) ;


-- -----------------------------------------------------
-- Table `electrodomesticos_store`.`tipo_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electrodomesticos_store`.`tipo_producto` (
  `id_stock` INT(11) NULL DEFAULT NULL,
  `nombre_tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre_tipo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `electrodomesticos_store`.`vale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electrodomesticos_store`.`vale` (
  `id_vale` INT(11) NOT NULL AUTO_INCREMENT,
  `valor` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id_vale`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `electrodomesticos_store`.`vale_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electrodomesticos_store`.`vale_cliente` (
  `id_vale` INT(11) NOT NULL,
  `id_cliente` INT(11) NOT NULL,
  PRIMARY KEY (`id_vale`, `id_cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

USE `electrodomesticos_store` ;

-- -----------------------------------------------------
-- Placeholder table for view `electrodomesticos_store`.`stock_sucursal_este`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electrodomesticos_store`.`stock_sucursal_este` (`id_stock` INT, `nombre` INT, `cantidad` INT, `precio` INT, `id_sucursal` INT);

-- -----------------------------------------------------
-- Placeholder table for view `electrodomesticos_store`.`stock_sucursal_norte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electrodomesticos_store`.`stock_sucursal_norte` (`id_stock` INT, `nombre` INT, `cantidad` INT, `precio` INT, `id_sucursal` INT);

-- -----------------------------------------------------
-- Placeholder table for view `electrodomesticos_store`.`stock_sucursal_oeste`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electrodomesticos_store`.`stock_sucursal_oeste` (`id_stock` INT, `nombre` INT, `cantidad` INT, `precio` INT, `id_sucursal` INT);

-- -----------------------------------------------------
-- Placeholder table for view `electrodomesticos_store`.`stock_sucursal_sur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electrodomesticos_store`.`stock_sucursal_sur` (`id_stock` INT, `nombre` INT, `cantidad` INT, `precio` INT, `id_sucursal` INT);

-- -----------------------------------------------------
-- View `electrodomesticos_store`.`stock_sucursal_este`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `electrodomesticos_store`.`stock_sucursal_este`;
USE `electrodomesticos_store`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `electrodomesticos_store`.`stock_sucursal_este` AS select `electrodomesticos_store`.`stock_productos`.`id_stock` AS `id_stock`,`electrodomesticos_store`.`stock_productos`.`nombre` AS `nombre`,`electrodomesticos_store`.`stock_productos`.`cantidad` AS `cantidad`,`electrodomesticos_store`.`stock_productos`.`precio` AS `precio`,`electrodomesticos_store`.`stock_productos`.`id_sucursal` AS `id_sucursal` from `electrodomesticos_store`.`stock_productos` PARTITION (`part3`);

-- -----------------------------------------------------
-- View `electrodomesticos_store`.`stock_sucursal_norte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `electrodomesticos_store`.`stock_sucursal_norte`;
USE `electrodomesticos_store`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `electrodomesticos_store`.`stock_sucursal_norte` AS select `electrodomesticos_store`.`stock_productos`.`id_stock` AS `id_stock`,`electrodomesticos_store`.`stock_productos`.`nombre` AS `nombre`,`electrodomesticos_store`.`stock_productos`.`cantidad` AS `cantidad`,`electrodomesticos_store`.`stock_productos`.`precio` AS `precio`,`electrodomesticos_store`.`stock_productos`.`id_sucursal` AS `id_sucursal` from `electrodomesticos_store`.`stock_productos` PARTITION (`part1`);

-- -----------------------------------------------------
-- View `electrodomesticos_store`.`stock_sucursal_oeste`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `electrodomesticos_store`.`stock_sucursal_oeste`;
USE `electrodomesticos_store`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `electrodomesticos_store`.`stock_sucursal_oeste` AS select `electrodomesticos_store`.`stock_productos`.`id_stock` AS `id_stock`,`electrodomesticos_store`.`stock_productos`.`nombre` AS `nombre`,`electrodomesticos_store`.`stock_productos`.`cantidad` AS `cantidad`,`electrodomesticos_store`.`stock_productos`.`precio` AS `precio`,`electrodomesticos_store`.`stock_productos`.`id_sucursal` AS `id_sucursal` from `electrodomesticos_store`.`stock_productos` PARTITION (`part4`);

-- -----------------------------------------------------
-- View `electrodomesticos_store`.`stock_sucursal_sur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `electrodomesticos_store`.`stock_sucursal_sur`;
USE `electrodomesticos_store`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `electrodomesticos_store`.`stock_sucursal_sur` AS select `electrodomesticos_store`.`stock_productos`.`id_stock` AS `id_stock`,`electrodomesticos_store`.`stock_productos`.`nombre` AS `nombre`,`electrodomesticos_store`.`stock_productos`.`cantidad` AS `cantidad`,`electrodomesticos_store`.`stock_productos`.`precio` AS `precio`,`electrodomesticos_store`.`stock_productos`.`id_sucursal` AS `id_sucursal` from `electrodomesticos_store`.`stock_productos` PARTITION (`part2`);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
