insert into stock_productos (id_stock, tipo, nombre, cantidad) values (1, 4, 'Depiladora', 47);
insert into stock_productos (id_stock, tipo, nombre, cantidad) values (2, 2, 'Campana extractora', 67);
insert into stock_productos (id_stock, tipo, nombre, cantidad) values (3, 4, 'Afeitadora', 56);
insert into stock_productos (id_stock, tipo, nombre, cantidad) values (4, 1, 'Home Cinema', 50);
insert into stock_productos (id_stock, tipo, nombre, cantidad) values (5, 2, 'Heladera', 93);
insert into stock_productos (id_stock, tipo, nombre, cantidad) values (6, 4, 'Cepillo electrico', 74);
insert into stock_productos (id_stock, tipo, nombre, cantidad) values (7, 3, 'Cafetera', 21);
insert into stock_productos (id_stock, tipo, nombre, cantidad) values (8, 3, 'Cafetera', 12);
insert into stock_productos (id_stock, tipo, nombre, cantidad) values (9, 4, 'Afeitadora', 9);
insert into stock_productos (id_stock, tipo, nombre, cantidad) values (10, 4, 'Afeitadora', 24);
insert into stock_productos (id_stock, tipo, nombre, cantidad) values (11, 2, 'Refrigerador', 88);
insert into stock_productos (id_stock, tipo, nombre, cantidad) values (12, 1, 'Reproductor de DVD', 40);
insert into stock_productos (id, tipo, nombre, cantidad) values (13, 4, 'Secador de pelo', 68);
insert into stock_productos (id, tipo, nombre, cantidad) values (14, 1, 'Reproductor de audio', 61);
insert into stock_productos (id, tipo, nombre, cantidad) values (15, 2, 'Horno', 41);
insert into stock_productos (id, tipo, nombre, cantidad) values (16, 4, 'Afeitadora', 78);
insert into stock_productos (id, tipo, nombre, cantidad) values (17, 1, 'Equipo de musica', 62);
insert into stock_productos (id, tipo, nombre, cantidad) values (18, 3, 'Tostadora', 10);
insert into stock_productos (id, tipo, nombre, cantidad) values (19, 5, 'Pulidora', 93);
insert into stock_productos (id, tipo, nombre, cantidad) values (20, 5, 'Plancha Aspiradora', 62);
insert into stock_productos (id, tipo, nombre, cantidad) values (21, 3, 'Cafetera', 66);
insert into stock_productos (id, tipo, nombre, cantidad) values (22, 4, 'Secador de pelo', 38);
insert into stock_productos (id, tipo, nombre, cantidad) values (23, 2, 'Campana extractora', 31);
insert into stock_productos (id, tipo, nombre, cantidad) values (24, 2, 'Lavadora', 80);
insert into stock_productos (id, tipo, nombre, cantidad) values (25, 5, 'Plancha Aspiradora', 49);
insert into stock_productos (id, tipo, nombre, cantidad) values (26, 3, 'Tostadora', 29);
insert into stock_productos (id, tipo, nombre, cantidad) values (27, 2, 'Nevera', 97);
insert into stock_productos (id, tipo, nombre, cantidad) values (28, 1, 'Reproductor de DVD', 85);
insert into stock_productos (id, tipo, nombre, cantidad) values (29, 3, 'Cafetera', 100);
insert into stock_productos (id, tipo, nombre, cantidad) values (30, 4, 'Cepillo electrico', 18);
insert into stock_productos (id, tipo, nombre, cantidad) values (31, 5, 'Pulidora', 91);
insert into stock_productos (id, tipo, nombre, cantidad) values (32, 1, 'Reproductor de Vídeo', 1);
insert into stock_productos (id, tipo, nombre, cantidad) values (33, 3, 'Cafetera', 36);
insert into stock_productos (id, tipo, nombre, cantidad) values (34, 3, 'Cafetera', 48);
insert into stock_productos (id, tipo, nombre, cantidad) values (35, 5, 'Ventilador', 45);
insert into stock_productos (id, tipo, nombre, cantidad) values (36, 3, 'Multiprocesadora', 91);
insert into stock_productos (id, tipo, nombre, cantidad) values (37, 1, 'Equipo de musica', 53);
insert into stock_productos (id, tipo, nombre, cantidad) values (38, 2, 'Estufa domestica', 32);
insert into stock_productos (id, tipo, nombre, cantidad) values (39, 2, 'Lavadora', 14);
insert into stock_productos (id, tipo, nombre, cantidad) values (40, 2, 'Heladera', 41);
